#!/usr/bin/env python3
"""Generate the FORGE_ICONS block for review_server.py from the forge-icons repo.

Run from the knowledge repo with the forge-icons checkout available. Writes the block to stdout
so it can be inspected before being pasted in - the path data is machine-generated and nobody
should be hand-editing it.
"""
import pathlib
import re
import sys

FI = pathlib.Path("/Users/vijay.venkataraman@tylertech.com/Library/CloudStorage/"
                  "OneDrive-TylerTechnologies,Inc/Repo/claude/tcp-cli/forge-icons/svg")

# name -> (why this icon, what it replaced)
WANT = [
    ("flag",                  "My Transcripts - the queue flagged as yours", "U+1F6A9"),
    ("clipboard_list",        "All Transcripts - the whole queue", "U+1F4CB"),
    ("chart_bar",             "OT Analytics", "U+1F4CA"),
    ("publish",               "Save & Share - commit and send in", "U+1F4E4"),
    ("source_pull",           "PRs - the icon for a pull request", "U+1F500"),
    ("backup_restore",        "Config Backups, including the restore actions", "U+1F4BE"),
    ("folder",                "a directory in the snapshot browser", "U+1F4C1"),
    ("file_document_outline", "a file in the snapshot browser", "U+1F4C4"),
    ("refresh",               "every refresh and sync button", "U+21BB"),
    ("magnify",               "the search field", "U+1F50D"),
    ("thumb_up",              "positive Foundry feedback on a transcript", "U+1F44D"),
    ("thumb_down",            "negative Foundry feedback on a transcript", "U+1F44E"),
    ("menu",                  "the empty-state glyph", "U+2630"),
    ("chevron_down",          "column filter caret, and an open disclosure", "U+25BE"),
    ("chevron_right",         "a closed disclosure", "U+25B8"),
]


def path_of(name):
    f = FI / (name + ".svg")
    if not f.is_file():
        sys.exit("missing icon: " + name)
    svg = f.read_text(encoding="utf-8")
    vb = re.search(r'viewBox="([^"]+)"', svg)
    if not vb or vb.group(1) != "0 0 24 24":
        sys.exit("unexpected viewBox on " + name)
    # Skip the transparent 24x24 bounding rect several icons carry - it is layout padding for
    # the sprite, and keeping it would make every icon a filled square if fill is ever set on
    # the path rather than the svg.
    paths = [m.group(1) for m in re.finditer(r'<path[^>]*\bd="([^"]+)"', svg)
             if 'fill="none"' not in m.group(0)]
    if not paths:
        sys.exit("no drawable path in " + name)
    return " ".join(paths)


print('# ---------------------------------------------------------------------------------------------')
print('# Tyler Forge icons.')
print('#')
print('# Generated by scripts/gen_icons.py from the forge-icons repo - DO NOT HAND-EDIT the path')
print('# data. Regenerate if an icon needs changing, so the source of truth stays the icon set.')
print('#')
print('# WHY THE PATHS ARE INLINE rather than served as files. This is a single-file app that runs')
print('# from memory on loopback; adding a static-file route plus fifteen files to fetch would be')
print('# more machinery than the 2.2 KB of path data it replaces. Inline SVG also inherits')
print('# currentColor, which is what lets one icon work in both display modes and take a per-item')
print('# tint - see nav.side .ic below.')
print('#')
print('# THESE REPLACED EMOJI, and the swap is not purely cosmetic. Emoji render from a font, so')
print('# they differed per platform - the same nav looked different on macOS and Windows - they')
print('# could not be tinted, and they carried their own baked-in colour that fought the theme.')
print('FORGE_ICONS = {')
w = max(len(n) for n, _, _ in WANT)
for name, why, was in WANT:
    print(f'    # {why} (was {was})')
    print(f'    {name!r}: ("{path_of(name)}"),')
print('}')
